package org.alter.cockpit.workorders

import org.alter.cockpit.Json

/** Turns one kind of enrichment into files. Generated code is a reviewed starting point, never merged blindly. */
interface ScaffoldGenerator {
    val kind: String

    fun supports(enrichment: Enrichment): Boolean

    fun generate(enrichment: Enrichment, params: Map<String, Any?>, ctx: ScaffoldContext): Scaffold
}

/** What generators need besides the enrichment: RSCM names and which content packages exist. */
class ScaffoldContext(val names: RscmNames, private val packageExists: (String) -> Boolean) {
    /** `areas/<location>/npcs` when that package exists (e.g. Lumbridge), else a `generated` package. */
    fun npcPackage(location: String?): String {
        val slug = location?.let(RscmNames::slug)?.takeIf { it.isNotEmpty() }
        val area = slug?.let { "org.alter.plugins.content.areas.$it.npcs" }
        return area?.takeIf(packageExists) ?: "org.alter.plugins.content.generated"
    }

    fun objPackage(): String = "org.alter.plugins.content.generated"

    fun npcName(id: Int, pageName: String?): String = names.name("npc", id) ?: "npc.${RscmNames.slug(pageName ?: "npc")}_$id"

    fun objName(id: Int, pageName: String?): String = names.name("object", id) ?: "object.${RscmNames.slug(pageName ?: "obj")}_$id"

    fun itemName(pageName: String): String? = names.nameFor("item", pageName)
}

class ScaffoldService(private val generators: List<ScaffoldGenerator>, private val ctx: ScaffoldContext) {
    fun generate(enrichment: Enrichment, params: Map<String, Any?>): Scaffold {
        val generator = generators.firstOrNull { it.supports(enrichment) } ?: throw IllegalStateException("No scaffold generator for ${enrichment.kind} cards")
        return generator.generate(enrichment, params, ctx)
    }
}

internal object Kt {
    fun className(name: String): String = name.split(Regex("""[^A-Za-z0-9]+""")).filter { it.isNotEmpty() }.joinToString("") { it.replaceFirstChar(Char::uppercase) }

    fun str(text: String): String = "\"" + text.replace("\\", "\\\\").replace("\"", "\\\"").replace("$", "\${'$'}") + "\""

    fun packagePath(pkg: String): String = "game-plugins/src/main/kotlin/" + pkg.replace('.', '/')

    fun header(pkg: String, sources: List<Source>, what: String, extraImports: List<String> = emptyList()): String = buildString {
        appendLine("package $pkg")
        appendLine()
        (listOf("org.alter.api.ext.*", "org.alter.game.Server", "org.alter.game.model.World", "org.alter.game.model.entity.Player", "org.alter.game.model.queue.QueueTask", "org.alter.game.plugin.KotlinPlugin", "org.alter.game.plugin.PluginRepository") + extraImports)
            .sorted().forEach { appendLine("import $it") }
        appendLine()
        appendLine("/**")
        appendLine(" * $what")
        appendLine(" * Generated by the Dev Cockpit from the OSRS Wiki (CC BY-NC-SA 3.0); review before merging.")
        sources.forEach { appendLine(" * Source: ${it.url}") }
        appendLine(" */")
    }

    fun branch(kind: String, name: String, id: Int) = "cockpit/$kind-${RscmNames.slug(name).take(40)}-$id"
}

/** `talk-to`: a plugin whose dialogue mirrors the transcript's standard section. */
class DialogueGenerator : ScaffoldGenerator {
    override val kind = "dialogue"

    override fun supports(enrichment: Enrichment) = enrichment.kind == "talk-to" && enrichment.transcript != null

    override fun generate(enrichment: Enrichment, params: Map<String, Any?>, ctx: ScaffoldContext): Scaffold {
        val id = (params["id"] as Number).toInt()
        val name = enrichment.facts["name"] as? String ?: enrichment.page?.title ?: "Npc"
        val rscm = ctx.npcName(id, enrichment.page?.title)
        val pkg = ctx.npcPackage(enrichment.facts["location"] as? String)
        val cls = Kt.className(name) + "Plugin"
        val transcript = enrichment.transcript!!
        val standard = transcript.sections.firstOrNull { it.title.equals("Standard dialogue", true) && it.parent == null }
            ?: transcript.sections.firstOrNull { !it.questDependent } ?: transcript.sections.first()
        val skipped = transcript.sections.filter { it !== standard }
        val manual = buildList {
            if (skipped.isNotEmpty()) add("Not generated (${skipped.joinToString(", ") { it.title }}): quest-state or situational dialogue.")
            if (transcript.incomplete) add("The wiki marks this transcript as incomplete.")
            if (transcript.opens().isNotEmpty()) add("Shops opened here need their own definition: ${transcript.opens().joinToString()}.")
            if (ctx.names.name("npc", id) == null) add("$rscm is not in data/cfg/rscm/npc.rscm; check the name.")
        }
        val code = buildString {
            append(Kt.header(pkg, enrichment.sources, "$name: Talk-to dialogue.", listOf("kotlin.random.Random")))
            appendLine("class $cls(r: PluginRepository, world: World, server: Server) : KotlinPlugin(r, world, server) {")
            appendLine("    init {")
            appendLine("        onNpcOption(${Kt.str(rscm)}, option = \"talk-to\") {")
            appendLine("            player.queue { dialog(player) }")
            appendLine("        }")
            appendLine("    }")
            appendLine()
            appendLine("    suspend fun QueueTask.dialog(player: Player) {")
            emit(standard.body, "        ", this)
            appendLine("    }")
            if (skipped.isNotEmpty()) {
                appendLine()
                appendLine("    // Sections not generated: " + skipped.joinToString("; ") { (it.parent?.let { p -> "$p › " } ?: "") + it.title })
            }
            appendLine("}")
        }
        return Scaffold(kind, "Dialogue plugin for $name ($rscm) from the wiki transcript", Kt.branch(kind, name, id), listOf(ScaffoldFile("${Kt.packagePath(pkg)}/$cls.kt", code)), manual)
    }

    private fun emit(nodes: List<Node>, indent: String, out: StringBuilder) {
        if (nodes.isEmpty()) out.appendLine("${indent}// (nothing)")
        nodes.forEach { node ->
            when (node) {
                is Node.Line -> out.appendLine("$indent${if (node.player) "chatPlayer" else "chatNpc"}(player, ${Kt.str(node.text)})")
                is Node.Options -> {
                    out.appendLine("${indent}when (options(player, ${node.options.joinToString(", ") { Kt.str(it.label) }})) {")
                    node.options.forEachIndexed { i, option ->
                        out.appendLine("$indent    ${i + 1} -> {")
                        emit(option.body, "$indent        ", out)
                        out.appendLine("$indent    }")
                    }
                    out.appendLine("$indent}")
                }
                is Node.Random -> {
                    out.appendLine("${indent}when (Random.nextInt(${node.options.size})) { // ${node.options.size} random variants")
                    node.options.forEachIndexed { i, option ->
                        out.appendLine("$indent    $i -> { // ${option.label}")
                        emit(option.body, "$indent        ", out)
                        out.appendLine("$indent    }")
                    }
                    out.appendLine("$indent}")
                }
                is Node.Action -> when (node.kind) {
                    Node.Action.END -> Unit
                    Node.Action.OPENS -> out.appendLine("${indent}player.openShop(${Kt.str(node.target ?: "")}) // TODO: define this shop with createShop")
                    Node.Action.ABOVE -> out.appendLine("${indent}// same as above")
                    Node.Action.RECEIVES -> out.appendLine("${indent}// TODO: the player receives ${node.target}")
                    else -> out.appendLine("${indent}// TODO: ${node.text}")
                }
                is Node.Condition -> {
                    out.appendLine("${indent}if (false) { // TODO: ${node.text}")
                    emit(node.body, "$indent    ", out)
                    out.appendLine("$indent}")
                }
                is Node.Note -> {
                    out.appendLine("${indent}// ${node.text}")
                    emit(node.body, indent, out)
                }
            }
        }
    }
}

/** `trade`: a plugin that defines the shop with its wiki stock and opens it on Trade. */
class ShopGenerator : ScaffoldGenerator {
    override val kind = "shop"

    override fun supports(enrichment: Enrichment) = enrichment.kind == "trade" && enrichment.shop != null

    override fun generate(enrichment: Enrichment, params: Map<String, Any?>, ctx: ScaffoldContext): Scaffold {
        val id = (params["id"] as Number).toInt()
        val shop = enrichment.shop!!
        val npc = enrichment.page?.title ?: params["name"] as? String ?: "Shop keeper"
        val rscm = ctx.npcName(id, npc)
        val pkg = ctx.npcPackage(shop.location)
        val cls = Kt.className(shop.name) + "Plugin"
        val unknown = mutableListOf<String>()
        val items = shop.stock.joinToString("\n") { line ->
            val name = ctx.itemName(line.item) ?: "item.${RscmNames.slug(line.item)}".also { unknown += line.item }
            "        ShopItem(getRSCM(${Kt.str(name)}), ${line.stock ?: 0}, ${line.sellPrice ?: "null"}, ${line.buyPrice ?: "null"}),"
        }
        val code = buildString {
            append(Kt.header(pkg, enrichment.sources, "${shop.name}: stock from the wiki, opened by $npc.", listOf("org.alter.game.model.shop.PurchasePolicy", "org.alter.game.model.shop.ShopItem", "org.alter.plugins.content.mechanics.shops.CoinCurrency", "org.alter.rscm.RSCM.getRSCM")))
            appendLine("class $cls(r: PluginRepository, world: World, server: Server) : KotlinPlugin(r, world, server) {")
            appendLine("    private val stock = listOf(")
            appendLine(items)
            appendLine("    )")
            appendLine()
            appendLine("    init {")
            appendLine("        createShop(${Kt.str(shop.name)}, CoinCurrency(), purchasePolicy = PurchasePolicy.${if (shop.specialty.equals("General store", true)) "BUY_TRADEABLES" else "BUY_STOCK"}) {")
            appendLine("            stock.forEachIndexed { index, item -> items[index] = item }")
            appendLine("        }")
            appendLine()
            appendLine("        onNpcOption(${Kt.str(rscm)}, option = \"trade\") {")
            appendLine("            player.openShop(${Kt.str(shop.name)})")
            appendLine("        }")
            appendLine("    }")
            appendLine("}")
        }
        val manual = buildList {
            if (unknown.isNotEmpty()) add("Items not found in data/cfg/rscm/item.rscm (check the names): ${unknown.joinToString()}.")
            if (shop.currency != null && !shop.currency.equals("Coins", true)) add("The shop trades in ${shop.currency}, not coins; CoinCurrency is a placeholder.")
            add("Restock times (${shop.stock.mapNotNull { it.restockTicks }.distinct().joinToString()} ticks on the wiki) are not applied; ShopItem uses the defaults.")
        }
        return Scaffold(kind, "Shop plugin for ${shop.name} (${shop.stock.size} items) opened by $rscm", Kt.branch(kind, shop.name, id), listOf(ScaffoldFile("${Kt.packagePath(pkg)}/$cls.kt", code)), manual)
    }
}

/** `pickpocket`: an entry for data/cfg/thieving/pickpockets.json. */
class PickpocketGenerator : ScaffoldGenerator {
    override val kind = "pickpocket"

    override fun supports(enrichment: Enrichment) = enrichment.kind == "pickpocket" && !enrichment.pickpocket.isNullOrEmpty()

    override fun generate(enrichment: Enrichment, params: Map<String, Any?>, ctx: ScaffoldContext): Scaffold {
        val id = (params["id"] as Number).toInt()
        val name = enrichment.page?.title ?: params["name"] as? String ?: "npc"
        val rscm = ctx.npcName(id, name)
        val unknown = mutableListOf<String>()
        val loot = enrichment.pickpocket!!.map { line ->
            val (min, max) = quantity(line.quantity)
            mapOf(
                "item" to (ctx.itemName(line.item) ?: "item.${RscmNames.slug(line.item)}".also { unknown += line.item }),
                "min" to min, "max" to max, "weight" to weight(line.rarity),
            )
        }
        val entry = mapOf(
            "npcs" to listOf(rscm),
            "level" to (enrichment.pickpocket.firstNotNullOfOrNull { it.level } ?: 1),
            "experience" to 0.0,
            "baseSuccess" to 0.55,
            "successBonusPerLevel" to 0.015,
            "stun" to mapOf("ticks" to 7, "damage" to mapOf("min" to 1, "max" to 1)),
            "loot" to loot,
        )
        val json = Json.prettyLf.writeValueAsString(entry)
        val manual = buildList {
            add("experience is 0.0: take the thieving xp from the wiki's Pickpocket table.")
            add("stun (7 ticks, 1 damage) and success rates are the defaults for low-level targets; check the wiki.")
            if (unknown.isNotEmpty()) add("Items not found in data/cfg/rscm/item.rscm: ${unknown.joinToString()}.")
        }
        return Scaffold(kind, "Pickpocket entry for $rscm with ${loot.size} loot lines", Kt.branch(kind, name, id), listOf(ScaffoldFile("data/cfg/thieving/pickpockets.json", json, ScaffoldFile.JSON_APPEND)), manual)
    }

    private fun quantity(text: String): Pair<Int, Int> {
        val numbers = Regex("""\d+""").findAll(text.replace(",", "")).map { it.value.toInt() }.toList()
        return when (numbers.size) {
            0 -> 1 to 1
            1 -> numbers[0] to numbers[0]
            else -> numbers[0] to numbers[1]
        }
    }

    /** Percent chance from the wiki rarity: `Always` → 100, `1/128` → 0.78. */
    private fun weight(rarity: String): Double {
        if (rarity.equals("Always", true)) return 100.0
        val m = Regex("""([\d.]+)/([\d,.]+)""").find(rarity) ?: return 1.0
        val d = m.groupValues[2].replace(",", "").toDoubleOrNull() ?: return 1.0
        return Math.round(100.0 * m.groupValues[1].toDouble() / d * 10_000) / 10_000.0
    }
}

/** `scenery` Open/Close: a single-door entry whose opened id a human must find. */
class DoorGenerator : ScaffoldGenerator {
    override val kind = "door"

    override fun supports(enrichment: Enrichment) = enrichment.kind == "scenery" && enrichment.target == "door or gate config"

    override fun generate(enrichment: Enrichment, params: Map<String, Any?>, ctx: ScaffoldContext): Scaffold {
        val id = (params["id"] as Number).toInt()
        val name = enrichment.page?.title ?: params["name"] as? String ?: "door"
        val closed = if ((params["optionName"] as? String).equals("Open", true)) id else -1
        val opened = if (closed == -1) id else -1
        val json = Json.prettyLf.writeValueAsString(mapOf("closed" to closed, "opened" to opened))
        return Scaffold(
            kind, "Single-door entry for $name ($id); the other state's id is unknown", Kt.branch(kind, name, id),
            listOf(ScaffoldFile("data/cfg/doors/single-doors.json", json, ScaffoldFile.JSON_APPEND, applyable = false)),
            listOf("Replace -1 with the object id of the ${if (closed == -1) "closed" else "opened"} door (the cache has both variants next to each other), then the entry can be applied."),
        )
    }
}

/** `scenery` Climb: a plugin stub with the destination left to a human. */
class TransportGenerator : ScaffoldGenerator {
    override val kind = "transport"

    override fun supports(enrichment: Enrichment) = enrichment.kind == "scenery" && enrichment.target == "transport stub"

    override fun generate(enrichment: Enrichment, params: Map<String, Any?>, ctx: ScaffoldContext): Scaffold {
        val id = (params["id"] as Number).toInt()
        val name = enrichment.page?.title ?: params["name"] as? String ?: "object"
        val option = (params["optionName"] as? String ?: "climb").lowercase()
        val rscm = ctx.objName(id, name)
        val pkg = ctx.objPackage()
        val cls = Kt.className("$name ${option}") + "Plugin"
        val code = buildString {
            append(Kt.header(pkg, enrichment.sources, "$name: $option."))
            appendLine("class $cls(r: PluginRepository, world: World, server: Server) : KotlinPlugin(r, world, server) {")
            appendLine("    init {")
            appendLine("        onObjOption(${Kt.str(rscm)}, option = ${Kt.str(option)}) {")
            appendLine("            // TODO: player.moveTo(x, z, height) for the destination; the wiki does not publish tiles.")
            appendLine("            player.message(\"TODO: $option destination\")")
            appendLine("        }")
            appendLine("    }")
            appendLine("}")
        }
        return Scaffold(kind, "Transport stub for $option on $name ($rscm)", Kt.branch(kind, name, id), listOf(ScaffoldFile("${Kt.packagePath(pkg)}/$cls.kt", code)), listOf("Choose the destination tile; the wiki has no coordinates."))
    }
}

/** `recipe`: a production stub for the first recipe (item on object or item on item). */
class RecipeGenerator : ScaffoldGenerator {
    override val kind = "recipe"

    override fun supports(enrichment: Enrichment) = enrichment.kind == "recipe" && !enrichment.recipes.isNullOrEmpty()

    override fun generate(enrichment: Enrichment, params: Map<String, Any?>, ctx: ScaffoldContext): Scaffold {
        val id = (params["id"] as Number).toInt()
        val usedId = (params["usedId"] as? Number)?.toInt() ?: -1
        val recipe = enrichment.recipes!!.first()
        val onObject = params["type"] == "ITEM_ON_LOC"
        val material = enrichment.facts["material"] as? String ?: recipe.materials.firstOrNull()?.first ?: "item"
        val target = enrichment.page?.title ?: params["name"] as? String ?: "target"
        val itemName = ctx.itemName(material) ?: "item.${RscmNames.slug(material)}"
        val targetName = if (onObject) ctx.objName(id, target) else (ctx.itemName(target) ?: "item.${RscmNames.slug(target)}")
        val outputName = ctx.itemName(recipe.output) ?: "item.${RscmNames.slug(recipe.output)}"
        val pkg = ctx.objPackage()
        val cls = Kt.className("${recipe.output} from ${material}") + "Plugin"
        val skill = recipe.skill?.uppercase()?.replace(' ', '_')
        val code = buildString {
            append(Kt.header(pkg, enrichment.sources, "${recipe.output} from $material${if (onObject) " at $target" else " with $target"}.", listOf("org.alter.api.Skills", "org.alter.rscm.RSCM.getRSCM")))
            appendLine("class $cls(r: PluginRepository, world: World, server: Server) : KotlinPlugin(r, world, server) {")
            appendLine("    init {")
            appendLine("        ${if (onObject) "onItemOnObj(obj = ${Kt.str(targetName)}, item = ${Kt.str(itemName)})" else "onItemOnItem(item1 = ${Kt.str(itemName)}, item2 = ${Kt.str(targetName)})"} {")
            appendLine("            player.queue { make(player) }")
            appendLine("        }")
            appendLine("    }")
            appendLine()
            appendLine("    suspend fun QueueTask.make(player: Player) {")
            if (skill != null && recipe.level != null) {
                appendLine("        if (player.getSkills().getCurrentLevel(Skills.$skill) < ${recipe.level}) {")
                appendLine("            player.message(\"You need a ${recipe.skill} level of ${recipe.level} to make ${recipe.output}.\")")
                appendLine("            return")
                appendLine("        }")
            }
            appendLine("        // TODO: animation and the wiki's ${recipe.ticks ?: "?"}-tick duration")
            recipe.materials.forEach { (name, qty) -> appendLine("        player.inventory.remove(getRSCM(${Kt.str(ctx.itemName(name) ?: "item.${RscmNames.slug(name)}")}), ${qty.toIntOrNull() ?: 1})") }
            appendLine("        player.inventory.add(getRSCM(${Kt.str(outputName)}), ${recipe.outputQuantity?.toIntOrNull() ?: 1})")
            if (skill != null && recipe.experience != null) appendLine("        player.addXp(Skills.$skill, ${recipe.experience})")
            appendLine("    }")
            appendLine("}")
        }
        val manual = buildList {
            if (enrichment.recipes.size > 1) add("Only the first of ${enrichment.recipes.size} recipes is generated (${enrichment.recipes.joinToString { it.output }}).")
            add("Animation, timing and failure (e.g. burning) are not on the wiki in a usable form.")
            if (usedId < 0 && onObject) add("The used item id was not recorded on the card.")
        }
        return Scaffold(kind, "Production stub: ${recipe.output} from $material", Kt.branch(kind, recipe.output, id), listOf(ScaffoldFile("${Kt.packagePath(pkg)}/$cls.kt", code)), manual)
    }
}

/** Anything else with a page: a plugin skeleton with the matching hook. */
class SkeletonGenerator : ScaffoldGenerator {
    override val kind = "skeleton"

    override fun supports(enrichment: Enrichment) = true

    override fun generate(enrichment: Enrichment, params: Map<String, Any?>, ctx: ScaffoldContext): Scaffold {
        val id = (params["id"] as Number).toInt()
        val type = params["type"] as? String ?: "UNKNOWN"
        val name = enrichment.facts["name"] as? String ?: enrichment.page?.title ?: params["name"] as? String ?: type.lowercase()
        val option = (params["optionName"] as? String)?.lowercase()
        val pkg = ctx.objPackage()
        val cls = Kt.className("$name ${option ?: type.lowercase()}") + "Plugin"
        val hook = when (type) {
            "NPC_OP" -> "onNpcOption(${Kt.str(ctx.npcName(id, enrichment.page?.title))}, option = ${Kt.str(option ?: "talk-to")})"
            "LOC_OP" -> "onObjOption(${Kt.str(ctx.objName(id, enrichment.page?.title))}, option = ${Kt.str(option ?: "use")})"
            else -> null
        }
        val code = buildString {
            append(Kt.header(pkg, enrichment.sources, "$name: $type${option?.let { " ($it)" } ?: ""}."))
            appendLine("class $cls(r: PluginRepository, world: World, server: Server) : KotlinPlugin(r, world, server) {")
            appendLine("    init {")
            if (hook != null) {
                appendLine("        $hook {")
                appendLine("            player.message(\"TODO: $name $option\")")
                appendLine("        }")
            } else {
                appendLine("        // TODO: $type $id (${enrichment.facts["examine"] ?: "no wiki facts"}); no generated hook for this interaction type.")
            }
            appendLine("    }")
            appendLine("}")
        }
        return Scaffold(kind, "Plugin skeleton for $type on $name", Kt.branch(kind, name, id), listOf(ScaffoldFile("${Kt.packagePath(pkg)}/$cls.kt", code)), listOf("Everything: this is only the hook."))
    }
}
