package org.alter.cockpit.workorders

import com.fasterxml.jackson.module.kotlin.convertValue
import io.github.oshai.kotlinlogging.KotlinLogging
import kotlinx.coroutines.CoroutineDispatcher
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import org.alter.cockpit.Json
import org.alter.cockpit.auth.Principal
import org.alter.cockpit.inbox.ApiException
import org.alter.cockpit.inbox.InboxAction
import org.alter.cockpit.inbox.InboxService

/**
 * The second half of a work order: from a card's enrichment to files on a branch. `scaffold` generates and
 * previews (files written to the card's worktree, staged, diffed); `apply` compiles the worktree through the
 * [CompileGate] and commits only when it passes; `discard` removes the worktree and branch. Everything is
 * stored on the card's result so the UI and later sessions see it.
 *
 * `apply` returns at once with `compile.state = "compiling"` and finishes on [scope] (off the request thread:
 * a Gradle run may take minutes), attaching `passed` + `applied`, or `failed` with the compiler's `e:` lines.
 */
class WorkOrders(
    private val inbox: InboxService,
    private val scaffolds: ScaffoldService,
    private val workspace: ScaffoldWorkspace,
    private val gate: CompileGate = NoopCompileGate,
    private val scope: CoroutineScope = CoroutineScope(Dispatchers.IO),
    private val compileDispatcher: CoroutineDispatcher = Dispatchers.IO,
) {
    private val logger = KotlinLogging.logger {}

    fun scaffold(id: String, principal: Principal): InboxAction {
        val card = inbox.get(id)
        val scaffold = scaffolds.generate(enrichmentOf(card), card.params)
        val preview = workspace.preview(id, scaffold)
        return inbox.attachResult(id, principal, "workorder.scaffold", mapOf("scaffold" to scaffold, "preview" to preview, "applied" to null, "compile" to null), mapOf("branch" to scaffold.branch, "files" to scaffold.files.map { it.path }))
    }

    fun apply(id: String, principal: Principal): InboxAction {
        val card = inbox.get(id)
        val scaffold = card.result?.get("scaffold")?.let { Json.mapper.convertValue<Scaffold>(it) } ?: throw ApiException(409, "Generate the scaffold first")
        if (compileState(card) == COMPILING) throw ApiException(409, "This card is already compiling")
        val message = "${scaffold.summary}\n\nGenerated by the Dev Cockpit from card ${card.title}."
        val started = inbox.attachResult(
            id, principal, "workorder.apply.start",
            mapOf("compile" to mapOf("state" to COMPILING, "task" to gate.task), "applied" to null),
            mapOf("branch" to scaffold.branch, "task" to gate.task),
        )
        scope.launch(compileDispatcher) {
            val (patch, details) = try {
                val applied = workspace.apply(id, scaffold, message, gate)
                mapOf("compile" to compileMap(PASSED, applied.compile), "applied" to applied) to mapOf("branch" to applied.branch, "commit" to applied.commit, "compileMs" to applied.compile.durationMs)
            } catch (e: CompileFailed) {
                logger.info { "Card $id did not compile: ${e.result.errors.size} error lines" }
                mapOf("compile" to compileMap(FAILED, e.result), "applied" to null) to mapOf("branch" to scaffold.branch, "errors" to e.result.errors.size, "compileMs" to e.result.durationMs)
            } catch (e: Exception) {
                logger.warn(e) { "Applying card $id failed" }
                mapOf("compile" to mapOf("state" to ERROR, "task" to gate.task, "errors" to listOf(e.message ?: e::class.simpleName)), "applied" to null) to mapOf("branch" to scaffold.branch, "error" to (e.message ?: e::class.simpleName))
            }
            try {
                inbox.attachResult(id, principal, "workorder.apply", patch, details)
            } catch (e: Exception) {
                logger.warn(e) { "Could not record the apply result for card $id" }
            }
        }
        return started
    }

    fun discard(id: String, principal: Principal): InboxAction {
        val card = inbox.get(id)
        if (compileState(card) == COMPILING) throw ApiException(409, "This card is compiling; wait for it to finish")
        val branch = (card.result?.get("scaffold") as? Map<*, *>)?.get("branch") as? String
        workspace.discard(id, branch)
        return inbox.attachResult(id, principal, "workorder.discard", mapOf("scaffold" to null, "preview" to null, "applied" to null, "compile" to null), mapOf("branch" to branch))
    }

    private fun compileState(card: InboxAction): String? = (card.result?.get("compile") as? Map<*, *>)?.get("state") as? String

    private fun compileMap(state: String, result: CompileResult) =
        mapOf("state" to state, "task" to result.task, "errors" to result.errors, "durationMs" to result.durationMs)

    private fun enrichmentOf(card: InboxAction): Enrichment {
        val result = card.result?.takeIf { it["kind"] != null } ?: throw ApiException(409, "The card has no enrichment yet; press GO first")
        return Json.mapper.convertValue(result - setOf("pageUrl", "scaffold", "preview", "applied", "compile"))
    }

    companion object {
        const val COMPILING = "compiling"
        const val PASSED = "passed"
        const val FAILED = "failed"
        const val ERROR = "error"
    }
}
