package org.alter.cockpit.workorders

import com.fasterxml.jackson.module.kotlin.convertValue
import org.alter.cockpit.Json
import org.alter.cockpit.auth.Principal
import org.alter.cockpit.inbox.ApiException
import org.alter.cockpit.inbox.InboxAction
import org.alter.cockpit.inbox.InboxService

/**
 * The second half of a work order: from a card's enrichment to files on a branch. `scaffold` generates and
 * previews (files written to the card's worktree, staged, diffed); `apply` commits; `discard` removes the
 * worktree and branch. Everything is stored on the card's result so the UI and later sessions see it.
 */
class WorkOrders(private val inbox: InboxService, private val scaffolds: ScaffoldService, private val workspace: ScaffoldWorkspace) {

    fun scaffold(id: String, principal: Principal): InboxAction {
        val card = inbox.get(id)
        val scaffold = scaffolds.generate(enrichmentOf(card), card.params)
        val preview = workspace.preview(id, scaffold)
        return inbox.attachResult(id, principal, "workorder.scaffold", mapOf("scaffold" to scaffold, "preview" to preview, "applied" to null), mapOf("branch" to scaffold.branch, "files" to scaffold.files.map { it.path }))
    }

    fun apply(id: String, principal: Principal): InboxAction {
        val card = inbox.get(id)
        val scaffold = card.result?.get("scaffold")?.let { Json.mapper.convertValue<Scaffold>(it) } ?: throw ApiException(409, "Generate the scaffold first")
        val applied = workspace.apply(id, scaffold, "${scaffold.summary}\n\nGenerated by the Dev Cockpit from card ${card.title}.")
        return inbox.attachResult(id, principal, "workorder.apply", mapOf("applied" to applied), mapOf("branch" to applied.branch, "commit" to applied.commit))
    }

    fun discard(id: String, principal: Principal): InboxAction {
        val card = inbox.get(id)
        val branch = (card.result?.get("scaffold") as? Map<*, *>)?.get("branch") as? String
        workspace.discard(id, branch)
        return inbox.attachResult(id, principal, "workorder.discard", mapOf("scaffold" to null, "preview" to null, "applied" to null), mapOf("branch" to branch))
    }

    private fun enrichmentOf(card: InboxAction): Enrichment {
        val result = card.result?.takeIf { it["kind"] != null } ?: throw ApiException(409, "The card has no enrichment yet; press GO first")
        return Json.mapper.convertValue(result - setOf("pageUrl", "scaffold", "preview", "applied"))
    }
}
